version: '3'


services: 

  user:
    image: user-service
    networks:
      - account
    depends_on:
      - transaction
    ports:
      - 8080:8080

  transaction:
    image: transaction-service
    networks:
      - account
    ports:
      - 8081:8080


networks:
    account: